const API_BASE_URL_DEVELOPMENT = 'https://localhost:7237';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const ENDPOINTS = {
    GET_PRICES_EDIT: "prices/edit",
    GET_PRICES_LIST: "prices/list",
    GET_PRICES_ITEM: "prices/item",
    GET_PRICES_ITEM_ELEMENT: "prices/item/element",
    GET_PRICES_ITEM_ELEMENT_DELETE: "prices/item/element/delete"
};

const development = {
    API_URL_GET_PRICES_EDIT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PRICES_EDIT}`,
    API_URL_GET_PRICES_LIST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PRICES_LIST}`,
    API_URL_GET_PRICES_ITEM: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PRICES_ITEM}`,
    API_URL_GET_PRICES_ITEM_ELEMENT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PRICES_ITEM_ELEMENT}`,
    API_URL_GET_PRICES_ITEM_ELEMENT_DELETE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PRICES_ITEM_ELEMENT_DELETE}`,
}

const production = {
    API_URL_GET_PRICES_EDIT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PRICES_EDIT}`,
    API_URL_GET_PRICES_LIST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PRICES_LIST}`,
    API_URL_GET_PRICES_ITEM: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PRICES_ITEM}`,
    API_URL_GET_PRICES_ITEM_ELEMENT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PRICES_ITEM_ELEMENT}`,
    API_URL_GET_PRICES_ITEM_ELEMENT_DELETE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PRICES_ITEM_ELEMENT_DELETE}`,
}

const Urls = process.env.NODE_ENV === "development" ? development : production;

export default Urls;